### ISSUE TITLE
Firefox containertabs + prune

### ISSUE THREAD

**Issue by charims** [tbrockman/prune#365]
**Is your feature request related to a problem? Please describe.**
There are some times(perhaps rare) where I want to have the same URL open multiple times. I use firefox container tabs, which greatly increases my ability to segment my various workloads. IE: Personal tabs vs Work tabs. Sometimes I want to open a new container tab and have it go to an existing URL, but it gets force-closed by prune. I right-click the tab and click "Open in New container tab" and then select the container I want to open it in "Work", whereupon it is immediately force-closed by prune.

**Describe the solution you'd like**
It would be wonderful if prune could tell it was a different container, and therefore not prune it.

**Describe alternatives you've considered**
I could disable auto-pruning, but I really like the behavior otherwise...

**Comment by tbrockman** [comment]
Interesting! I've never thought about how prune would interact with containers (even though I use Firefox myself I've rarely used them 👀), I'll take a look into what can be done to fix this as that does sound pretty frustrating, thanks for the report.

**Comment by tbrockman** [comment]
@charims Pushed the changes and seems to work. It's currently available on the Firefox Add-ons store, so unless you're making your own builds you should notice the new option (it's enabled by default since it seems like it generally works as expected in terms of focusing and closing duplicates across containers) when the app updates:
![image](https://github.com/user-attachments/assets/55d4515a-b2b1-4efb-a687-5c08e05ec616)

Gonna close this for now, feel free to re-open if something isn't working!
